site_name: Wingo Wiki
site_url: https://wingo-wiki.netlify.app
site_description: Wingo's personal wiki

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
  palette:
    scheme: slate
    primary: indigo
    accent: indigo

plugins:
  - search
  - roamlinks
  - glightbox

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tabbed
  - admonition
  - pymdownx.details
  - attr_list
  - footnotes

extra_javascript:
  - https://fastly.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js
  - https://fastly.jsdelivr.net/npm/echarts@5.5.0/dist/echarts.min.js
  - assets/javascripts/graph.js

extra_css:
  - assets/stylesheets/graph.css

nav:
  - Home: index.md
  - Concepts: concepts/
  - Comparisons: comparisons/
  - Entities: entities/
  - Queries: queries/