# WIKILINK_MAP: wikilink stem → short_filename
WIKILINK_MAP = {
    "advanced-tool-use": "advanced-tool-use.md",
    "agent-architecture": "agent-architecture.md",
    "agent-framework-practice": "agent-framework-practice.md",
    "agent-framework-theory": "agent-framework-theory.md",
    "agent-skills": "agent-skills.md",
    "beyond-permission-prompts": "beyond-permission-prompts.md",
    "building-effective-agents": "building-effective-agents.md",
    "claude-agent-sdk": "claude-agent-sdk.md",
    "claude-code-best-practices": "claude-code-best-practices.md",
    "claude-desktop-extensions": "claude-desktop-extensions.md",
    "claude-postmortem": "claude-postmortem.md",
    "context-engineering": "context-engineering.md",
    "context-management": "context-management.md",
    "contextual-retrieval": "contextual-retrieval.md",
    "dual-memory-system": "dual-memory-system.md",
    "effective-context-engineering": "effective-context-engineering.md",
    "hyde": "hyde.md",
    "interview-agent-arch": "interview-agent-arch.md",
    "interview-context-mgmt": "interview-context-mgmt.md",
    "interview-hyde": "interview-hyde.md",
    "langgraph": "langgraph.md",
    "long-running-agents": "long-running-agents.md",
    "mcp": "mcp.md",
    "mcp-code-execution": "mcp-code-execution.md",
    "mcp-deep-dive": "mcp-deep-dive.md",
    "multi-agent": "multi-agent.md",
    "multi-agent-research": "multi-agent-research.md",
    "prompt-injection": "prompt-injection.md",
    "rag": "rag.md",
    "react": "react.md",
    "slash-commands": "slash-commands.md",
    "swe-bench": "swe-bench.md",
    "think-tool": "think-tool.md",
    "tool-use": "tool-use.md",
    "writing-effective-tools": "writing-effective-tools.md",
    "ai-agent": "ai-agent.md",
    "anthropic": "anthropic.md",
    "claude-code": "claude-code.md",
    "langgraph-vs-react": "langgraph-vs-react.md",
    "interview-overview": "interview-overview.md",
    "interview-qa-overview": "interview-qa-overview.md",
    "session-context": "session-context.md",
}

# CATEGORY_MAP: short_filename → (category, subcategory)
CATEGORY_MAP = {
    "agent-architecture.md": ("agent-architecture", "core"),
    "agent-framework-theory.md": ("agent-architecture", "core"),
    "interview-agent-arch.md": ("agent-architecture", "interview"),
    "agent-framework-practice.md": ("agent-architecture", "practice"),
    "building-effective-agents.md": ("agent-architecture", "practice"),
    "claude-agent-sdk.md": ("claude", "practice"),
    "claude-code-best-practices.md": ("claude", "practice"),
    "claude-desktop-extensions.md": ("claude", "practice"),
    "claude-postmortem.md": ("claude", "practice"),
    "context-engineering.md": ("context-engineering", "core"),
    "context-management.md": ("context-engineering", "core"),
    "interview-context-mgmt.md": ("context-engineering", "interview"),
    "effective-context-engineering.md": ("context-engineering", "practice"),
    "mcp.md": ("mcp", "core"),
    "mcp-code-execution.md": ("mcp", "practice"),
    "mcp-deep-dive.md": ("mcp", "practice"),
    "multi-agent.md": ("multi-agent", "core"),
    "multi-agent-research.md": ("multi-agent", "practice"),
    "langgraph.md": ("other", "core"),
    "prompt-injection.md": ("other", "core"),
    "react.md": ("other", "core"),
    "agent-skills.md": ("other", "practice"),
    "beyond-permission-prompts.md": ("other", "practice"),
    "dual-memory-system.md": ("other", "practice"),
    "long-running-agents.md": ("other", "practice"),
    "slash-commands.md": ("other", "practice"),
    "swe-bench.md": ("other", "practice"),
    "contextual-retrieval.md": ("rag", "core"),
    "hyde.md": ("rag", "core"),
    "rag.md": ("rag", "core"),
    "interview-hyde.md": ("rag", "interview"),
    "advanced-tool-use.md": ("tool-use", "core"),
    "tool-use.md": ("tool-use", "core"),
    "think-tool.md": ("tool-use", "practice"),
    "writing-effective-tools.md": ("tool-use", "practice"),
    "ai-agent.md": ("entities", ""),
    "anthropic.md": ("entities", ""),
    "claude-code.md": ("entities", ""),
    "langgraph-vs-react.md": ("comparisons", ""),
    "interview-overview.md": ("queries", ""),
    "interview-qa-overview.md": ("queries", ""),
    "session-context.md": ("queries", ""),
}
